# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
	pod 'SnapKit', '~> 5.0.0'
	 pod 'RxSwift', '~> 5'
target 'DemoObjectDetection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoObjectDetection

end
