project 'AdventureOfBamboo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdventureOfBamboo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 5.0'

  # Pods for AdventureOfBamboo

end
